version: "3.8"

services:
  torrentfastcleaner:
    build: .
    container_name: torrentfastcleaner
    restart: no
    environment:
      HA_WEBHOOK_URL: ${HA_WEBHOOK_URL} #triggering next app after complting current app tasks
      HA_WEBHOOKERROR_URL: ${HA_WEBHOOKERROR_URL}
      QBITIP: ${QBITIP}
      QBITUSER: ${QBITUSER}
      QBITPASS: ${QBITPASS}

    dns:
      - 1.1.1.1
      - 1.0.0.1





