version: "3.8"

services:
  torrentfastcleaner:
    build: .
    container_name: torrentfastcleaner
    restart: no
    environment:
      HA_WEBHOOK_URL_RADARR: ${HA_WEBHOOK_URL_RADARR} #triggering next app after complting current app tasks
      HA_WEBHOOKERROR_URL: ${HA_WEBHOOKERROR_URL}
      HA_WEBHOOK_URL_SONARR: ${HA_WEBHOOK_URL_SONARR}
      QBITIP: ${QBITIP}
      QBITUSER: ${QBITUSER}
      QBITPASS: ${QBITPASS}
      TIME: ${TIME}

    dns:
      - 1.1.1.1
      - 1.0.0.1





